### ISSUE TITLE
Line not break when zitemize contains too much items

### ISSUE THREAD

**Issue by xiazeyu** [TimmyChan/data-science-tech-resume-template#1]
If my zitemize contains too much items, the line won't break.
eg. in `sections/activities.md`

```latex
\subsection{{Section}}
\begin{zitemize}
\item test \hfill  test
\item test \hfill  test
\item test \hfill  test
\item test \hfill  test
\item test \hfill  test
\item test \hfill  test
\item test \hfill  test
\item test \hfill  test
\item test \hfill  test
\item test \hfill  test
\item test \hfill  test
\item test \hfill  test
\item test \hfill  test
\item test \hfill  test
\item test \hfill  test
\item test \hfill  test
\item test \hfill  test
\end{zitemize}
```

It will just turns like:
![image](https://user-images.githubusercontent.com/10560038/156963008-8980ded3-612e-4e22-9fbf-84c62b78ccfd.png)

**Comment by xiazeyu** [comment]
`\newpage` can help, but I don't know if there're automatical ways doing that

**Comment by TimmyChan** [comment]
zitemize is rly itemize with a couple of options put in

% tighter spacing than itemize
\setlist[itemize]{align=parleft,left=0pt..1em}
\newenvironment{zitemize}{
\begin{itemize} \itemsep 0pt \parskip 0pt \parsep 1pt}
{\end{itemize}\vspace{-.5em}}

I'm not entirely sure why that's happening I'll have to read a little --- in the mean time, why so many items? I built this with the assumption that one would edit it down to one page; perhaps I should fork this and build a CV template and tackle this problem there?

**Comment by xiazeyu** [comment]
It seems that it was worked in yout latest template in Overleaf. Is it correct?

**Comment by TimmyChan** [comment]
> It seems that it was worked in yout latest template in Overleaf. Is it correct?

I believe so; I haven't seen this issue after tinkering with fancyhdr and page style for unrelated reasons? 

Let me know if the issue persists :)

**Comment by xiazeyu** [comment]
It works for me. Just don't know if there are any way to leave some blank at the bottom of the page when break a new line. Current it just leave no space when the content is full, seems not quite elegent for me.
